<a href="https://colab.research.google.com/github/abraham-john-paul/AppliedAICourse/blob/main/1_Python_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
# A   = [[1, 3, 4],
#        [2, 5, 7],
#         [5, 9, 6]]
# B   = [[1, 0, 0],
#        [0, 1, 0],
#        [0, 0, 1]]
A   = [[1, 2],
        [3, 4]]
B   = [[1, 2, 3, 4, 5],
        [5, 6, 7, 8, 9]]

def matrix_mul(A, B):
    # write your code
    if not A or not B:
        return 'Not possible'
    
    nrowA, ncolA = len(A), len(A[0])
    nrowB, ncolB = len(B), len(B[0])
    
    if ncolA != nrowB:
        return 'Not possible'
    
    res = [[0 for i in range(ncolB)] for j in range(nrowA)]

    for i in range(nrowA):
        for j in range(ncolB):
            for k in range(ncolA):
                res[i][j] += A[i][k] * B[k][j]
    
    return res
    
matrix_mul(A, B)

[[11, 14, 17, 20, 23], [23, 30, 37, 44, 51]]

<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [ ]:
from random import uniform
from bisect import bisect_right
from collections import Counter
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

A = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]
# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    total = sum(A)
    cum_sum_list = [A[0]/total]
    for i in A[1:]:
        cum_sum_list.append(cum_sum_list[-1] + i/total)
    random_no = uniform(0, 1)
    return A[bisect_right(cum_sum_list, random_no, 0, len(A))]

def sampling_based_on_magnitued():
    number = []
    for i in range(1,100):
        number.append(pick_a_number_from_list(A))
    print(Counter(number))

sampling_based_on_magnitued()

Counter({100: 29, 79: 23, 45: 14, 27: 14, 28: 9, 6: 3, 10: 3, 13: 3, 5: 1})


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [ ]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
    res = ""
    for c in String:
        if c.isnumeric():
            res += "#"
    
    return res # modified string which is after replacing the # with digits
    
ip = ['234', 'a2b3c4', 'abc', '#2a$#b%c%561#']
for i in ip:
    print(replace_digits(i))

###
###

####


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [ ]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
def display_dash_board(students, marks):
    n = len(students)
    marks, students = zip(*sorted(zip(marks, students)))
    # write code for computing top top 5 students
    top_5_students = zip(students[n - 1:(n - 5 - 1): -1], marks[n - 1:(n - 5 - 1): -1])
    # write code for computing top least 5 students
    least_5_students = zip(students[:5], marks[:5])
    # write code for computing top least 5 students
    pos_of_25th_percentile = math.ceil((25 * n) / 100) - 1
    pos_of_75th_percentile = math.ceil((75 * n) / 100) - 1
    students_within_25_and_75 = zip(students[pos_of_25th_percentile: pos_of_75th_percentile], marks[pos_of_25th_percentile: pos_of_75th_percentile])
    
    return top_5_students, least_5_students, students_within_25_and_75
students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10']
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)
for i in "abc":
    print(i)
    if i == 'a':
        pstudents, pmarks = zip(*top_5_students)
    elif i == 'b':
        pstudents, pmarks = zip(*least_5_students)
    else:
        pstudents, pmarks = zip(*students_within_25_and_75)
    for student, mark in zip(pstudents, pmarks):
        print(student, mark)

a
student8 98
student10 80
student2 78
student5 48
student7 47
b
student3 12
student4 14
student9 35
student6 43
student1 45
c
student9 35
student6 43
student1 45
student7 47
student5 48


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [ ]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    p, q = P
    distance = []
    sum_psq_and_qsq = (p**2 + q**2)

    for x, y in S:
        value = math.acos((x*p + y*q)/(math.pow((x**2 + y**2)*sum_psq_and_qsq, 0.5)))
        distance.append(value)
    _, points = zip(*sorted(zip(distance, S)))

    return points[:5]
    # return closest_points_to_p  # its list of tuples

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1), (6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
print(*points, sep='\n')

(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [ ]:
import math
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    start = 0
    params = [float(i) for i in re.findall(r'-?\d+\.?\d*', line)]
    
    nblue = len(blue)
    nred = len(red) 
    isRight = True if params[0] * red[0][0] + params[1] * red[0][1] + params[2] >= 0 else False
    for x, y in red[1:]:
        value = True if params[0] * x + params[1] * y + params[2] >= 0 else False
        if isRight != value:
            return 'NO'

    isRight = True if params[0] * blue[0][0] + params[1] * blue[0][1] + params[2] >= 0 else False
    for x, y in blue[1:]:
        value = True if params[0] * x + params[1] * y + params[2] >= 0 else False
        if isRight != value:
            return 'NO'
    
    return 'YES'
    

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [2]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def curve_smoothing(string):
    pos_value = {}
    string_list = string.strip().split(',')
    for i, s in enumerate(string_list):
        if s.isnumeric():
            pos_value[i] = int(s)
    res = []
    start = 0
    n = 0
    for i in pos_value.keys():
        if start < i:
            n = i - start + 1
            if start not in pos_value.keys():
                q, r = divmod(pos_value[i],  n)
                q = q if r == 0 else pos_value[i] / n
                res.extend([q] * n)
            else:
                q, r = divmod(pos_value[i] + pos_value[start],  n)
                q = q if r == 0 else (pos_value[i] + pos_value[start]) / n
                res = res[:start] + [q] * n
            start = i
        pos_value[i] = res[-1]
    else:
        n = len(string_list)
        if start != n - 1:
            n =  n - start
            q, r = divmod(res[-1],  n)
            q = q if r == 0 else res[-1] / n
            res = res[:len(res) -1] + [q] * n
        
    return res

S=  "_,_,30,_,_,_,50,_,_"
smoothed_values = curve_smoothing(S)
print(','.join(map(str, smoothed_values)))

10,10,12,12,12,12,4,4,4


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings



# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    nS1, nS2, nS3 = 0, 0, 0
    nF1S1, nF2S1, nF3S1, nF4S1, nF5S1 = 0, 0, 0, 0, 0
    nF1S2, nF2S2, nF3S2, nF4S2, nF5S2 = 0, 0, 0, 0, 0 
    nF1S3, nF2S3, nF3S3, nF4S3, nF5S3 = 0, 0, 0, 0, 0

    for f, s in A:
        if s == 'S1':
            nS1 += 1
            if f == 'F1':
                nF1S1 += 1
            elif f == 'F2':
                nF2S1 += 1
            elif f == 'F3':
                nF3S1 += 1
            elif f == 'F4':
                nF4S1 += 1
            else:
               nF5S1 += 1 
        elif s == 'S2':
            nS2 += 1
            if f == 'F1':
                nF1S2 += 1
            elif f == 'F2':
                nF2S2 += 1
            elif f == 'F3':
                nF3S2 += 1
            elif f == 'F4':
                nF4S2 += 1
            else:
               nF5S2 += 1 
        else:
            nS3 += 1
            if f == 'F1':
                nF1S3 += 1
            elif f == 'F2':
                nF2S3 += 1
            elif f == 'F3':
                nF3S3 += 1
            elif f == 'F4':
                nF4S3 += 1
            else:
               nF5S3 += 1
    print(f'a. P(F=F1|S==S1)={nF1S1}/{nS1}, P(F=F1|S==S2)={nF1S2}/{nS2}, P(F=F1|S==S3)={nF1S3}/{nS3}')
    print(f'b. P(F=F2|S==S1)={nF2S1}/{nS1}, P(F=F2|S==S2)={nF2S2}/{nS2}, P(F=F2|S==S3)={nF2S3}/{nS3}')
    print(f'c. P(F=F3|S==S1)={nF3S1}/{nS1}, P(F=F3|S==S2)={nF3S2}/{nS2}, P(F=F3|S==S3)={nF3S3}/{nS3}')
    print(f'd. P(F=F4|S==S1)={nF4S1}/{nS1}, P(F=F4|S==S2)={nF4S2}/{nS2}, P(F=F4|S==S3)={nF4S3}/{nS3}')
    print(f'e. P(F=F5|S==S1)={nF5S1}/{nS1}, P(F=F5|S==S2)={nF5S2}/{nS2}, P(F=F4|S==S3)={nF5S3}/{nS3}')

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F4|S==S3)=0/3


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    S1 = set(S1.strip().split(' '))
    S2 = set(S2.strip().split(' '))
    a = len(S1.intersection(S2))
    b = list(S1.difference(S2))
    c = list(S2.difference(S1))
    return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print('a.', a)
print('b.', b)
print('c.', c)

a. 7
b. ['5', 'first', 'F']
c. ['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
from math import log

# you can free to change all these codes/structure
def compute_log_loss(A):
    n = len(A)
    loss = 0

    for y, y_score in A:
        loss += ((y * log(y_score, 10)) + ((1 - y) * log(1 - y_score, 10)))

    return loss * (-1 / n)

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
